import colors from 'vuetify/es5/util/colors'
import minifyTheme from 'minify-css-string'

// process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

export default {
  // Global page headers: https://go.nuxtjs.dev/config-head
  ssr: false,
  head: {
    titleTemplate: '%s - ISKER Group',
    title: 'Главная страница',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=1280px, maximum-scale=1.0' },
      // { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'ISKER Group', name: 'ISKER Group', content: 'ISKER Group tender portal' },
      { name: 'format-detection', content: 'telephone=no' },
      { hid: 'og:locale', name: 'og:locale', content: 'ru_RU' },
      { hid: 'og:type', name: 'og:type', content: 'website' },
      { hid: 'og:title', name: 'og:title', content: 'ISKER Group' },
      { hid: 'og:description', name: 'og:description', content: 'ISKER Group tender portal' },
      { hid: 'og:image', name: 'og:image', content: '/icon.png' },
      { hid: 'og:url', name: 'og:url', content: 'http://tender.isker.kz/' },
      { hid: 'og:site_name', name: 'og:site_name', content: 'ISKER Group' }
    ],
    link: [
      { rel: 'icon', type: 'image/png', href: '/icon.png' }
    ]
  },
  server: {
    // host: '192.168.163.10', // default: localhost
    // port: 8080 // default: 3000

    host: '192.168.1.206',
    port: 8080 // default: 3000

    // host: '0.0.0.0', // docker
    // port: 3000 // docker
  },
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '~assets/css/main_styles.css',
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    // https://go.nuxtjs.dev/vuetify
    '@nuxtjs/vuetify',
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    '@nuxtjs/auth-next',
    'nuxt-material-design-icons-iconfont',
    'nuxt-i18n',
    '@nuxtjs/gtm'
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    // baseURL: 'http://127.0.0.1:8000/',
    baseURL: 'http://192.168.1.206:8000/',
    // baseURL: process.env.NODE_ENV === 'production' ? 'http://45.86.80.37:8000' : 'http://localhost:8000'
  },

  // PWA module configuration: https://go.nuxtjs.dev/pwa
  pwa: {
    manifest: {
      lang: 'en'
    }
  },

  // Vuetify module configuration: https://go.nuxtjs.dev/config-vuetify
  vuetify: {
    customVariables: ['~/assets/variables.scss'],
    theme: {
      dark: false,
      themes: {
        dark: {
          primary: colors.blue.darken2,
          accent: colors.shades.white,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3,
          alert: '#F3F7FF',
          cancellation: colors.shades.white,
          good: colors.blue,
          infolight: colors.teal.lighten5,
          confirmation: '#17AA00',
          refusal: '#E43945',
        },
        light: {
          primary: colors.blue.darken2,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: '#008071',
          warning: colors.amber.base,
          error: colors.red.darken3,
          success: colors.green.darken3,
          alert: '#F3F7FF',
          cancellation: colors.shades.white,
          good: colors.blue,
          infolight: colors.teal.lighten5,
          confirmation: '#17AA00',
          refusal: '#E43945',
        },
      },
    },
    options: { minifyTheme },
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    transpile: ['vuetify/lib'],
  },

  router: {
    middleware: ['auth'] // Перенаправление на Логин если не залогинился
  },

  auth: {
    strategies: {
      local: {
        scheme: 'refresh',
        localStorage: {
          prefix: 'auth.'
        },
        token: {
          prefix: 'access_token.',
          property: 'access',
          maxAge: 60,
          global: true,
          required: true,
          type: 'Bearer'
        },
        refreshToken:{
          prefix: 'refresh_token.',
          property: 'refresh',
          data: 'refresh',
          maxAge: 60 * 60 * 24 * 30
        },

        user: {
          property: 'user',
          autoFetch: true
        },
        endpoints: {
          login: { url: '/api/token/', method: 'post' },
          login_bin: { url: '/api/token_bin/', method: 'post' },
          refresh: { url: '/api/token/refresh/', method: 'post' },
          user: { url: '/api/v1/profile/', method: 'get' },
          logout: { url: '/api/logout/', method: 'post' }
        },
        redirect: {
          login: '/',
          logout: '/',
          callback: '/',
          home: '/',
        },
      },
      local_bin: {
        scheme: 'refresh',
        localStorage: {
          prefix: 'auth.'
        },
        token: {
          prefix: 'access_token.',
          property: 'access',
          maxAge: 60,
          global: true,
          required: true,
          type: 'Bearer'
        },
        refreshToken:{
          prefix: 'refresh_token.',
          property: 'refresh',
          data: 'refresh',
          maxAge: 60 * 60 * 24 * 30
        },

        user: {
          property: 'user',
          autoFetch: true
        },
        endpoints: {
          login: { url: '/api/token_bin/', method: 'post' },
          refresh: { url: '/api/token/refresh/', method: 'post' },
          user: { url: '/api/v1/profile/', method: 'get' },
          logout: { url: '/api/logout/', method: 'post' }
        },
        redirect: {
          login: '/',
          logout: '/',
          callback: '/',
          home: '/',
        },
      }
    },
    plugins: [ '~/plugins/auth.js' ],
  },

  i18n: {
    /* module options */
    locales: ['ru', 'en', 'kz'],
    defaultLocale: 'ru',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected',
      redirectOn: '/',
    },
    vueI18n: {
      fallbackLocale: 'ru',
      messages: {
        ru: {
          welcome: 'Добро пожаловать',
          main: 'ГЛАВНАЯ',
          title_main: 'Главная страница',
          search: 'Поиск',
          tenders: 'Тендеры',
          tender: 'Тендер',
          admin_panel: 'АДМИНКА',
          logout: 'Выйти',
          account: 'АККАУНТ',
          notifications: 'Уведомления',
          favourites: 'Избранное',
          profile: 'Профиль',
          settings: 'Настройки',
          users: 'Пользователи',
          login: 'Логин',

          start_date: 'Дата начала',
          end_date: 'Дата окончания',
          rfq_in_viewed: 'Просмотрен',
          rfq_in_not_viewed: 'Не просмотрен',
          rfq_in_accepted: 'Принят',
          rfq_in_declined: 'Отклонен',
          rfq_in_ignored: 'Без ответа',
          rfq_in_sent: 'КП отправлено',

          entered_as: 'Вы вошли как',
          search_by: 'Поиск тендера по номеру RFQ или описанию',
          add_favorites: 'Добавить в избранное',
          rfq_active: 'Активные',
          rfq_closed: 'Завершенные',
          rfq_all: 'Все',
          rfq_status: 'Статус',
          rfq_status_closed: 'Завершен',
          rfq_status_active: 'Активный',
          rfq_status_draft: 'Черновик',
          rfq_open: 'Открыть',
          rfq_no_data: 'Нет данных',

          footer_feedback: 'Обратная связь с ISKER',
          footer_instructions: 'Инструкции Тендерного портала',
          footer_feedback_title: 'Здесь Вы можете отправить свой вопрос',
          footer_feedback_title2: 'менеджеру компании ISKER',
          footer_feedback_email: 'Ваш e-mail',
          footer_feedback_email_ph: 'Укажите почту для связи с Вами',
          footer_feedback_name: 'Ваши ФИО',
          footer_feedback_name_ph: 'Укажите Ваши ФИО',
          footer_feedback_name_label: 'ФИО',
          footer_feedback_phone: 'Ваш номер телефона',
          footer_feedback_phone_ph: 'Укажите Ваш номер телефона для связи',
          footer_feedback_phone_label: 'Телефон',
          footer_feedback_rfq: 'Тема Вашего письма / Номер RFQ',
          footer_feedback_rfq_ph: 'Напишите здесь тему Вашего письма или Номер RFQ',
          footer_feedback_rfq_label: 'Тема письма',
          footer_feedback_text: 'Текст Вашего письма',
          footer_feedback_text_ph: 'Напишите здесь текст Вашего письма',
          footer_feedback_text_label: 'Текст письма',
          footer_feedback_sent: 'Ваше письмо отправлено',
          footer_feedback_err: 'Ошибка! Письмо не отправлено',
          cancel: 'Отмена',
          send: 'Отправить',
          close: 'Закрыть',

          rules_email: 'Введите Вашу почту',
          rules_email_err: 'Вы неправильно ввели почту',
          rules_empty: 'Это поле не может быть пустым',
          rules_max50: 'Максимум 50 символов',
          rules_max100: 'Максимум 100 символов',
          rules_max150: 'Максимум 150 символов',
          rules_max1000: 'Максимум 1000 символов',

          rfq_num: '№ RFQ заявки',
          rfq_description: 'Краткое описание тендера',
          rfq_date: 'Дата RFQ заявки',
          rfq_company: 'Организация',
          rfq_tender_status: 'Статус Тендера',
          rfq_period: 'Период проведения Тендера',
          rfq_period_start: 'Начало',
          rfq_period_end: 'Окончание',
          rfq_address: 'Условия и адрес поставки',
          rfq_payment: 'Условия оплаты',
          rfq_comment: 'Комментарий',
          rfq_accept: 'Принять участие',
          rfq_decline: 'Отказаться',
          rfq_accepted: 'Тендер принят',
          rfq_declined: 'Тендер отклонен',
          rfq_sent: 'КП отправлено',
          rfq_doc_form: 'Печатная форма RFQ',
          rfq_docs: 'Вложения RFQ',

          table_loading: 'Загрузка данных',
          table_err: 'Ошибка получения данных, попробуйте перезагрузить таблицу!',
          table_refresh: 'Перезагрузить таблицу',

          table_title: 'Номенклатуры',
          table_save: 'Сохранить',
          table_dialog_amount: 'Требуемое количество',
          table_dialog_measure: 'Ед.изм',
          table_dialog_term: 'Требуемый срок поставки',
          table_dialog_price: 'Цена за ед. без НДС',
          table_dialog_total: 'Сумма без НДС',
          table_dialog_term_enter: 'Укажите Ваш срок поставки',
          table_dialog_term_enter_ph: 'Напишите срок поставки',
          table_dialog_amount_change: 'Измените количество, если отличается от требуемого',
          table_dialog_amount_label: 'Количество',
          table_dialog_dms: 'Доля местного содержания, если имеется',
          table_dialog_dms_perc: '% ДМС',
          table_dialog_alter: 'Отклонения от требования (альтерантива) / Нет отклонения',
          table_dialog_alter_ph: 'Напишите отклонения от требования, если имеются',

          table_dialog_reset: 'Сбросить',
          table_dialog_close: 'Отменить',

          table_cell_have: 'Есть',
          table_cell_nope: 'Нет',
          table_cell_selected: 'Указан',
          table_cell_edit_title: 'Добавить в КП',
          table_cell_edit: 'Edit',
          table_cell_view_title: 'Посмотреть',
          table_cell_view: 'View',

          po_sent_date: 'Дата отправки КП',
          po_offered_amount: 'Предложенное количество',
          po_number: 'Номер Коммерческого предложения',
          po_number_set: 'Напишите номер Вашего Коммерческого предложения',
          po_error: 'Ошибка!',

          rows_currency: 'Выберите валюту',
          rows_no_nds: 'Итого без НДС',

          rows_terms: 'Свои условия оплаты',
          rows_terms_ph: 'Напишите Ваши условия оплаты, если отличаются от требуемых',
          rows_agent: 'ФИО представителя',
          rows_agent_ph: 'Напишите Ваше ФИО',
          rows_agent_pos: 'Должность представителя',
          rows_agent_pos_ph: 'Напишите Вашу должность',
          rows_agent_tel: 'Номер телефона представителя',
          rows_agent_tel_ph: 'Напишите Ваш номер мобильного телефона',
          files_add: 'Добавить еще файл',
          rows_comment: 'Комментарий',
          rows_comment_ph: 'Напишите комментарий к Вашему КП',
          po_send: 'Отправить Коммерческое Предложение',

          confirm_dialog_accept: 'Подтвердите участие в Тендере',
          dialog_warn: 'ПРЕДУПРЕЖДЕНИЕ!',
          confirm_dialog_warn2: 'После того, как Вы приняли тендер, Вам необходимо отправить КП до окончания периода проведения тендера. Отменить решение будет невозможно!',
          confirm_dialog_question: 'Вы действительно хотите принять участие в выбранном Тендере?',
          confirm_dialog_confirm: 'Подтвердить участие',

          decline_dialog_accept: 'Подтвердите ОТКАЗ от участия в Тендере',
          decline_dialog_warn2: 'После того, как Вы отклонили тендер, Вы больше не сможете принять в нем участие. Отменить решение будет невозможно!',
          decline_dialog_question: 'Вы действительно хотите отказаться от участия в выбранном Тендере?',
          decline_dialog_confirm: 'Подтвердить отказ',

          po_confirm: 'Подтвердите отправку',
          po_confirm2: 'Коммерческого предложения',

          po_warn: 'После подтверждения Вы больше не сможете вносить изменения в Вашем КП.',
          po_warn2: 'Отменить отправку будет невозможно!',
          po_question: 'Вы действительно хотите отправить',
          po_question2: 'Коммерческое предложение к текущему Тендеру',
          po_accept: 'Подтвердить отправку',

          po_sending: 'Ваше Коммерческое предложение',
          po_sending2: 'отправляется',

          po_not_sent: 'Ваше Коммерческое предложение',
          po_not_sent2: 'НЕ ОТПРАВЛЕНО!',
          po_repeat: 'Попробуйте отправить еще раз',
          po_repeat2: 'или обратитесь в службу поддержки!',
          refresh_page: 'Перезагрузить страницу',
          po_not_sent_fill: 'Чтобы отправить Ваше КП, необходимо',
          po_not_sent_fill2: 'заполнить данные хотя бы',
          po_not_sent_fill3: 'одной номенклатуры',
          continue: 'Продолжить',

          po_table_desc: 'Описание',
          po_table_item: 'Номенклатура',
          po_table_alter: 'Отклонения от требования',
          po_table_amount: 'Кол-во',
          po_table_measure: 'Ед. изм.',
          po_table_term: 'Срок поставки',
          po_table_quality: 'Сертификаты качества',
          po_table_rk: 'Сертификаты РК',
          items_alter_no: 'Нет',
          items_alter_yes: 'Да',

          po_rules_file: 'Максимальный размер файла 15МБ',
          po_rules_max: 'Максимум',
          po_rules_max2: 'символов',
          po_rules_required: 'Это поле обязательно к заполнению',
          po_rules_dms: 'Введите значение от 0 до 100',
          po_add_file_label: 'Прикрепить файл',
          tender_page: 'Страница тендера',

          snack_price: 'Необходимо указать цену!',
          snack_term: 'Необходимо указать срок поставки!',
          snack_saved: 'Cохранено!',
          snack_save_error: 'Ошибка сохранения! Попробуйте еще раз!',

          snack_tel: 'Укажите Телефон представителя',
          snack_pos: 'Укажите Должность представителя',
          snack_names: 'Укажите ФИО представителя',
          snack_currency: 'Укажите валюту КП',
          snack_num: 'Заполните номер КП',
          po_sent: 'Коммерческое предложение отправлено!',

          login_by_email: 'Вход по почте',
          login_by_bin: 'Вход по БИН',
          login_username: 'Имя пользователя',
          login_next: 'Далее',
          login_pass: 'Пароль',
          login_enter: 'Войти',
          login_restore: 'Восстановить пароль',
          login_code: 'Код подтверждения',
          login_code_ph: 'Введите код подтверждения',
          login_code_enter: 'Ввести код подтверждения',
          login_set_pass: 'Установите пароль для Вашего аккаунта',
          login_pass_enter: 'Введите пароль',
          login_pass_repeat: 'Повторите пароль',
          login_pass_save: 'Сохранить пароль и войти',
          login_code_send: 'Отправить код подтверждения на почту',
          login_confirm_rules: 'Даю свое',
          login_confirm_rules2: 'Согласие',
          login_confirm_rules3: 'Согласие на обработку персональных данных',
          login_confirm_rules4: 'на обработку персональных данных',
          login_user_bin: 'БИН пользователя',
          login_forgot_pass: 'Забыли пароль?',
          login_enter_bin: 'Ввести БИН',
          login_email_sent: 'На вашу почту',
          login_email_sent2: 'было отправлено письмо с кодом подтверждения',

          login_rules_username: 'Введите Имя пользователя',
          login_rules_username_err: 'Вы неправильно ввели Имя пользователя',
          login_rules_pass_req: 'Пароль обязательное поле',
          login_rules_pass_dig: 'Пароль должен содержать минимум одну цифру',
          login_rules_code_dig: 'Код подтверждения состоит из 6 цифр',
          login_rules_confirm: 'Подтвердите свое согласие',
          login_rules_auth: 'Авторизация',
          login_rules_pass_rep_err: 'Пароли не совпадают',
          login_rules_pass_err: 'Вы ввели неправильный пароль',
          login_rules_no_user: 'Пользователя с таким именем не существует',
          login_rules_no_bin: 'Пользователя с таким БИН не существует',
          login_rules_code_err: 'Вы ввели неправильный код подтверждения',

          profile_status_approved: 'Подтвержденный',
          profile_status_not_approved: 'Непроверенный',
          profile_contractor: 'Контрагент',
          profile_email: 'Электронная почта',
          profile_phone: 'Номер телефона',
          profile_website: 'Веб-сайт',
          profile_actual_addr: 'Фактический адрес',
          profile_legal_addr: 'Юридический адрес',
          profile_manager: 'Основной менеджер',
          profile_tabs_info: 'ИНФО',
          profile_tabs_bank: 'РЕКВИЗИТЫ',
          profile_tabs_contracts: 'КОНТРАКТЫ',
          profile_tabs_contacts: 'КОНТАКТНЫЕ ЛИЦА',

          profile_table_bank: 'Банковские реквизиты',
          profile_table_currency: 'Валюта',
          profile_table_account: 'Номер счета',
          profile_table_bank_name: 'Наименование банка',
          profile_table_bik: 'БИК',

          profile_table_number: 'Номер',
          profile_table_name: 'Рабочее наименование',
          profile_table_state: 'Текущее состояние',
          profile_table_from: 'Действует с',
          profile_table_to: 'Действует по',
          profile_table_pay_currency: 'Валюта взаиморасчетов',

          profile_table_FIO: 'ФИО',
          profile_table_pos: 'Должность по визитке',
          profile_table_phone: 'Номер телефона',
          profile_table_email: 'Электронная почта',

        },
        en: {
          welcome: 'Welcome',
          main: 'Home',
          title_main: 'Main Page',
          search: 'Search',
          tenders: 'Tenders',
          tender: 'Tender',
          admin_panel: 'Admin',
          logout: 'Logout',
          account: 'Account',
          notifications: 'Notifications',
          favourites: 'Favourites',
          profile: 'Profile',
          settings: 'Settings',
          users: 'Users',
          login: 'Login',

          start_date: 'Start date',
          end_date: 'End date',
          rfq_in_viewed: 'Viewed',
          rfq_in_not_viewed: 'Not viewed',
          rfq_in_accepted: 'Accepted',
          rfq_in_declined: 'Declined',
          rfq_in_ignored: 'Ignored',
          rfq_in_sent: 'PO sent',

          entered_as: 'You entered as',
          search_by: 'Search tender by RFQ number or description',
          add_favorites: 'Add to favorites',
          rfq_active: 'Active',
          rfq_closed: 'Closed',
          rfq_all: 'All',
          rfq_status: 'Status',
          rfq_status_closed: 'Closed',
          rfq_status_active: 'Active',
          rfq_status_draft: 'Draft',
          rfq_open: 'Open',
          rfq_no_data: 'No data',

          footer_feedback: 'Feedback from ISKER',
          footer_instructions: 'Tender Portal Instructions',
          footer_feedback_title: 'Here you can submit your question',
          footer_feedback_title2: 'ISKER company manager',
          footer_feedback_email: 'Your e-mail',
          footer_feedback_email_ph: 'Enter email address to contact you',
          footer_feedback_name: 'Your full name',
          footer_feedback_name_ph: 'Enter your full name',
          footer_feedback_name_label: 'Full name',
          footer_feedback_phone: 'Your phone number',
          footer_feedback_phone_ph: 'Enter your contact phone number',
          footer_feedback_phone_label: 'Phone',
          footer_feedback_rfq: 'Subject of your letter / RFQ number',
          footer_feedback_rfq_ph: 'Write here the subject of your letter or RFQ number',
          footer_feedback_rfq_label: 'Letter subject',
          footer_feedback_text: 'The text of your letter',
          footer_feedback_text_ph: 'Write here the text of your letter',
          footer_feedback_text_label: 'Text of the letter',
          footer_feedback_sent: 'Your letter has been sent',
          footer_feedback_err: 'Error! Letter not sent',
          cancel: 'Cancel',
          send: 'Send',
          close: 'Close',

          rules_email: 'Enter your email',
          rules_email_err: 'You entered your email incorrectly',
          rules_empty: 'This field cannot be empty',
          rules_max50: 'Maximum 50 characters',
          rules_max100: 'Maximum 100 characters',
          rules_max150: 'Maximum 150 characters',
          rules_max1000: 'Maximum 1000 characters',

          rfq_num: 'RFQ Application No.',
          rfq_description: 'Brief description of the tender',
          rfq_date: 'RFQ Application date',
          rfq_company: 'Organization',
          rfq_tender_status: 'Tender Status',
          rfq_period: 'Tender Period',
          rfq_period_start: 'Start',
          rfq_period_end: 'End',
          rfq_address: 'Terms and delivery address',
          rfq_payment: 'Terms of payment',
          rfq_comment: 'Comment',
          rfq_accept: 'Participate',
          rfq_decline: 'Refuse',
          rfq_accepted: 'Tender accepted',
          rfq_declined: 'Tender rejected',
          rfq_sent: 'PO sent',
          rfq_doc_form: 'Printable RFQ',
          rfq_docs: 'RFQ attachments',

          table_loading: 'Loading data',
          table_err: 'Error getting data, try to reload the table!',
          table_refresh: 'Reload table',

          table_title: 'Items',
          table_save: 'Save',
          table_dialog_amount: 'Required quantity',
          table_dialog_measure: 'Unit',
          table_dialog_term: 'Required delivery time',
          table_dialog_price: 'Price per one, no VAT',
          table_dialog_total: 'Price, no VAT',
          table_dialog_term_enter: 'Enter your delivery time',
          table_dialog_term_enter_ph: 'Write delivery time',
          table_dialog_amount_change: 'Change quantity, if different from required',
          table_dialog_amount_label: 'Quantity',
          table_dialog_dms: 'Share of local content, if any',
          table_dialog_dms_perc: '% LC',
          table_dialog_alter: 'Deviations from requirement (alternative) / No deviation',
          table_dialog_alter_ph: 'Write deviations from the requirement, if any',

          table_dialog_reset: 'Reset',
          table_dialog_close: 'Cancel',

          table_cell_have: 'Yes',
          table_cell_nope: 'No',
          table_cell_selected: 'Specified',
          table_cell_edit_title: 'Add to PO',
          table_cell_edit: 'Edit',
          table_cell_view_title: 'View',
          table_cell_view: 'View',

          po_sent_date: 'Дата отправки КП',
          po_offered_amount: 'Suggested Quantity',
          po_number: 'Number of Payment offer',
          po_number_set: 'Write the number of your Payment offer',
          po_error: 'Error!',

          rows_currency: 'Select currency',
          rows_no_nds: 'Total without VAT',

          rows_terms: 'Your payment terms',
          rows_terms_ph: 'Write your terms of payment, if different from the required',
          rows_agent: 'Full name of the representative',
          rows_agent_ph: 'Write your name',
          rows_agent_pos: 'Representative position',
          rows_agent_pos_ph: 'Write your position',
          rows_agent_tel: 'Representative phone number',
          rows_agent_tel_ph: 'Write your mobile phone number',
          files_add: 'Add more files',
          rows_comment: 'Comment',
          rows_comment_ph: 'Write a comment to your PO',
          po_send: 'Submit Payment Offer',

          confirm_dialog_accept: 'Confirm participation in the tender',
          dialog_warn: 'WARNING!',
          confirm_dialog_warn2: 'Once you have accepted the tender, you must send the PO before the end of the tender period. It will be impossible to cancel the decision!',
          confirm_dialog_question: 'Are you sure you want to participate in this Tender?',
          confirm_dialog_confirm: 'Confirm Participation',

          decline_dialog_accept: 'Confirm REFUSAL to participate in the Tender',
          decline_dialog_warn2: 'Once you have rejected a tender, you will no longer be able to participate in it. It will be impossible to cancel the decision!',
          decline_dialog_question: 'Are you sure you want to withdraw from the selected Tender?',
          decline_dialog_confirm: 'Confirm Denial',

          po_confirm: 'Confirm Price Offer',
          po_confirm2: 'sending',

          po_warn: 'After confirmation, you will no longer be able to make changes to your PO.',
          po_warn2: 'It will be impossible to cancel decision',
          po_question: 'Do you really want to send',
          po_question2: 'Price offer for the current Tender',
          po_accept: 'Confirm send',

          po_sending: 'Your Price Offer',
          po_sending2: 'is sending',

          po_not_sent: 'Your Price Offer',
          po_not_sent2: 'NOT SENT!',
          po_repeat: 'Try to send again',
          po_repeat2: 'or contact support!',
          refresh_page: 'Reload page',
          po_not_sent_fill: 'To send your quotation,',
          po_not_sent_fill2: 'you must fill in the data of',
          po_not_sent_fill3: 'at least one item',
          continue: 'Continue',

          po_table_desc: 'Description',
          po_table_item: 'Item',
          po_table_alter: 'Deviations from requirement',
          po_table_amount: 'Quantity',
          po_table_measure: 'Unit',
          po_table_term: 'Delivery time',
          po_table_quality: 'Quality certificates',
          po_table_rk: 'Certificates RK',
          items_alter_no: 'No',
          items_alter_yes: 'Yes',

          po_rules_file: 'Maximum file size 15MB',
          po_rules_max: 'Maximum',
          po_rules_max2: 'characters',
          po_rules_required: 'This field is required',
          po_rules_dms: 'Enter a value from 0 to 100',
          po_add_file_label: 'Attach file',
          tender_page: 'Tender page',

          snack_price: 'Price required!',
          snack_term: 'Delivery time is required!',
          snack_saved: 'Saved!',
          snack_save_error: 'Save error! Try again!',

          snack_tel: 'Enter the phone number of the representative',
          snack_pos: 'Enter the position of the representative',
          snack_names: 'Enter the name of the representative',
          snack_currency: 'Enter PO currency',
          snack_num: 'Enter PO number',
          po_sent: 'Price Offer sent!',

          login_by_email: 'Enter by email',
          login_by_bin: 'Enter by BIN',
          login_username: 'Username',
          login_next: 'Next',
          login_pass: 'Password',
          login_enter: 'Enter',
          login_restore: 'Restore password',
          login_code: 'Confirmation code',
          login_code_ph: 'Enter confirmation code',
          login_code_enter: 'Enter confirmation code',
          login_set_pass: 'Set Your account password',
          login_pass_enter: 'Enter password',
          login_pass_repeat: 'Repeat password',
          login_pass_save: 'Save password and enter',
          login_code_send: 'Send confirmation code to email',
          login_confirm_rules: 'Даю свое',
          login_confirm_rules2: 'Согласие',
          login_confirm_rules3: 'Согласие на обработку персональных данных',
          login_confirm_rules4: 'на обработку персональных данных',
          login_user_bin: 'users BIN',
          login_forgot_pass: 'Forgot password?',
          login_enter_bin: 'Enter BIN',
          login_email_sent: 'Confirmation code',
          login_email_sent2: 'has been sent to your email',

          login_rules_username: 'Enter username',
          login_rules_username_err: 'Username is incorrect',
          login_rules_pass_req: 'Password is required field',
          login_rules_pass_dig: 'Password must contain at least one digit',
          login_rules_code_dig: 'The confirmation code consists of 6 digits',
          login_rules_confirm: 'Confirm your consent',
          login_rules_auth: 'Authorization',
          login_rules_pass_rep_err: 'Passwords do not match',
          login_rules_pass_err: 'You entered the wrong password',
          login_rules_no_user: 'User with this name does not exist',
          login_rules_no_bin: 'User with this BIN does not exist',
          login_rules_code_err: 'You have entered an invalid confirmation code',

          profile_status_approved: 'Approved',
          profile_status_not_approved: 'Not approved',
          profile_contractor: 'Contractor',
          profile_email: 'Email',
          profile_phone: 'Phone number',
          profile_website: 'Web-site',
          profile_actual_addr: 'Actual address',
          profile_legal_addr: 'Legal address',
          profile_manager: 'General manager',
          profile_tabs_info: 'INFO',
          profile_tabs_bank: 'REQUISITES',
          profile_tabs_contracts: 'CONTRACTS',
          profile_tabs_contacts: 'CONTACTS',

          profile_table_bank: 'Bank details',
          profile_table_currency: 'Currency',
          profile_table_account: 'Account number',
          profile_table_bank_name: 'Name of the bank',
          profile_table_bik: 'BIC',

          profile_table_number: 'Number',
          profile_table_name: 'Working name',
          profile_table_state: 'Current state',
          profile_table_from: 'Valid from',
          profile_table_to: 'Valid until',
          profile_table_pay_currency: 'Settlement currency',

          profile_table_FIO: 'Full name',
          profile_table_pos: 'Position',
          profile_table_phone: 'Phone number',
          profile_table_email: 'Email',

        },
        kz: {
          welcome: 'Добро пожаловать',
          main: 'ГЛАВНАЯ',
          title_main: 'Главная страница',
          search: 'Поиск',
          tenders: 'Тендеры',
          tender: 'Тендер',
          admin_panel: 'АДМИНКА',
          logout: 'Выйти',
          account: 'АККАУНТ',
          notifications: 'Уведомления',
          favourites: 'Избранное',
          profile: 'Профиль',
          settings: 'Настройки',
          users: 'Пользователи',
          login: 'Логин',

          start_date: 'Дата начала',
          end_date: 'Дата окончания',
          rfq_in_viewed: 'Просмотрен',
          rfq_in_not_viewed: 'Не просмотрен',
          rfq_in_accepted: 'Принят',
          rfq_in_declined: 'Отклонен',
          rfq_in_ignored: 'Без ответа',
          rfq_in_sent: 'КП отправлено',

          entered_as: 'Вы вошли как',
          search_by: 'Поиск тендера по номеру RFQ или описанию',
          add_favorites: 'Добавить в избранное',
          rfq_active: 'Активные',
          rfq_closed: 'Завершенные',
          rfq_all: 'Все',
          rfq_status: 'Статус',
          rfq_status_closed: 'Завершен',
          rfq_status_active: 'Активный',
          rfq_status_draft: 'Черновик',
          rfq_open: 'Открыть',
          rfq_no_data: 'Нет данных',

          footer_feedback: 'Обратная связь с ISKER',
          footer_instructions: 'Инструкции Тендерного портала',
          footer_feedback_title: 'Здесь Вы можете отправить свой вопрос',
          footer_feedback_title2: 'менеджеру компании ISKER',
          footer_feedback_email: 'Ваш e-mail',
          footer_feedback_email_ph: 'Укажите почту для связи с Вами',
          footer_feedback_name: 'Ваши ФИО',
          footer_feedback_name_ph: 'Укажите Ваши ФИО',
          footer_feedback_name_label: 'ФИО',
          footer_feedback_phone: 'Ваш номер телефона',
          footer_feedback_phone_ph: 'Укажите Ваш номер телефона для связи',
          footer_feedback_phone_label: 'Телефон',
          footer_feedback_rfq: 'Тема Вашего письма / Номер RFQ',
          footer_feedback_rfq_ph: 'Напишите здесь тему Вашего письма или Номер RFQ',
          footer_feedback_rfq_label: 'Тема письма',
          footer_feedback_text: 'Текст Вашего письма',
          footer_feedback_text_ph: 'Напишите здесь текст Вашего письма',
          footer_feedback_text_label: 'Текст письма',
          footer_feedback_sent: 'Ваше письмо отправлено',
          footer_feedback_err: 'Ошибка! Письмо не отправлено',
          cancel: 'Отмена',
          send: 'Отправить',
          close: 'Закрыть',

          rules_email: 'Введите Вашу почту',
          rules_email_err: 'Вы неправильно ввели почту',
          rules_empty: 'Это поле не может быть пустым',
          rules_max50: 'Максимум 50 символов',
          rules_max100: 'Максимум 100 символов',
          rules_max150: 'Максимум 150 символов',
          rules_max1000: 'Максимум 1000 символов',

          rfq_num: '№ RFQ заявки',
          rfq_description: 'Краткое описание тендера',
          rfq_date: 'Дата RFQ заявки',
          rfq_company: 'Организация',
          rfq_tender_status: 'Статус Тендера',
          rfq_period: 'Период проведения Тендера',
          rfq_period_start: 'Начало',
          rfq_period_end: 'Окончание',
          rfq_address: 'Условия и адрес поставки',
          rfq_payment: 'Условия оплаты',
          rfq_comment: 'Комментарий',
          rfq_accept: 'Принять участие',
          rfq_decline: 'Отказаться',
          rfq_accepted: 'Тендер принят',
          rfq_declined: 'Тендер отклонен',
          rfq_sent: 'КП отправлено',
          rfq_doc_form: 'Печатная форма RFQ',
          rfq_docs: 'Вложения RFQ',

          table_loading: 'Загрузка данных',
          table_err: 'Ошибка получения данных, попробуйте перезагрузить таблицу!',
          table_refresh: 'Перезагрузить таблицу',

          table_title: 'Номенклатуры',
          table_save: 'Сохранить',
          table_dialog_amount: 'Требуемое количество',
          table_dialog_measure: 'Ед.изм',
          table_dialog_term: 'Требуемый срок поставки',
          table_dialog_price: 'Цена за ед. без НДС',
          table_dialog_total: 'Сумма без НДС',
          table_dialog_term_enter: 'Укажите Ваш срок поставки',
          table_dialog_term_enter_ph: 'Напишите срок поставки',
          table_dialog_amount_change: 'Измените количество, если отличается от требуемого',
          table_dialog_amount_label: 'Количество',
          table_dialog_dms: 'Доля местного содержания, если имеется',
          table_dialog_dms_perc: '% ДМС',
          table_dialog_alter: 'Отклонения от требования (альтерантива) / Нет отклонения',
          table_dialog_alter_ph: 'Напишите отклонения от требования, если имеются',

          table_dialog_reset: 'Сбросить',
          table_dialog_close: 'Отменить',

          table_cell_have: 'Есть',
          table_cell_nope: 'Нет',
          table_cell_selected: 'Указан',
          table_cell_edit_title: 'Добавить в КП',
          table_cell_edit: 'Edit',
          table_cell_view_title: 'Посмотреть',
          table_cell_view: 'View',

          po_sent_date: 'Дата отправки КП',
          po_offered_amount: 'Предложенное количество',
          po_number: 'Номер Коммерческого предложения',
          po_number_set: 'Напишите номер Вашего Коммерческого предложения',
          po_error: 'Ошибка!',

          rows_currency: 'Выберите валюту',
          rows_no_nds: 'Итого без НДС',

          rows_terms: 'Свои условия оплаты',
          rows_terms_ph: 'Напишите Ваши условия оплаты, если отличаются от требуемых',
          rows_agent: 'ФИО представителя',
          rows_agent_ph: 'Напишите Ваше ФИО',
          rows_agent_pos: 'Должность представителя',
          rows_agent_pos_ph: 'Напишите Вашу должность',
          rows_agent_tel: 'Номер телефона представителя',
          rows_agent_tel_ph: 'Напишите Ваш номер мобильного телефона',
          files_add: 'Добавить еще файл',
          rows_comment: 'Комментарий',
          rows_comment_ph: 'Напишите комментарий к Вашему КП',
          po_send: 'Отправить Коммерческое Предложение',

          confirm_dialog_accept: 'Подтвердите участие в Тендере',
          dialog_warn: 'ПРЕДУПРЕЖДЕНИЕ!',
          confirm_dialog_warn2: 'После того, как Вы приняли тендер, Вам необходимо отправить КП до окончания периода проведения тендера. Отменить решение будет невозможно!',
          confirm_dialog_question: 'Вы действительно хотите принять участие в выбранном Тендере?',
          confirm_dialog_confirm: 'Подтвердить участие',

          decline_dialog_accept: 'Подтвердите ОТКАЗ от участия в Тендере',
          decline_dialog_warn2: 'После того, как Вы отклонили тендер, Вы больше не сможете принять в нем участие. Отменить решение будет невозможно!',
          decline_dialog_question: 'Вы действительно хотите отказаться от участия в выбранном Тендере?',
          decline_dialog_confirm: 'Подтвердить отказ',

          po_confirm: 'Подтвердите отправку',
          po_confirm2: 'Коммерческого предложения',

          po_warn: 'После подтверждения Вы больше не сможете вносить изменения в Вашем КП.',
          po_warn2: 'Отменить отправку будет невозможно!',
          po_question: 'Вы действительно хотите отправить',
          po_question2: 'Коммерческое предложение к текущему Тендеру',
          po_accept: 'Подтвердить отправку',

          po_sending: 'Ваше Коммерческое предложение',
          po_sending2: 'отправляется',

          po_not_sent: 'Ваше Коммерческое предложение',
          po_not_sent2: 'НЕ ОТПРАВЛЕНО!',
          po_repeat: 'Попробуйте отправить еще раз',
          po_repeat2: 'или обратитесь в службу поддержки!',
          refresh_page: 'Перезагрузить страницу',
          po_not_sent_fill: 'Чтобы отправить Ваше КП, необходимо',
          po_not_sent_fill2: 'заполнить данные хотя бы',
          po_not_sent_fill3: 'одной номенклатуры',
          continue: 'Продолжить',

          po_table_desc: 'Описание',
          po_table_item: 'Номенклатура',
          po_table_alter: 'Отклонения от требования',
          po_table_amount: 'Кол-во',
          po_table_measure: 'Ед. изм.',
          po_table_term: 'Срок поставки',
          po_table_quality: 'Сертификаты качества',
          po_table_rk: 'Сертификаты РК',
          items_alter_no: 'Нет',
          items_alter_yes: 'Да',

          po_rules_file: 'Максимальный размер файла 15МБ',
          po_rules_max: 'Максимум',
          po_rules_max2: 'символов',
          po_rules_required: 'Это поле обязательно к заполнению',
          po_rules_dms: 'Введите значение от 0 до 100',
          po_add_file_label: 'Прикрепить файл',
          tender_page: 'Страница тендера',

          snack_price: 'Необходимо указать цену!',
          snack_term: 'Необходимо указать срок поставки!',
          snack_saved: 'Cохранено!',
          snack_save_error: 'Ошибка сохранения! Попробуйте еще раз!',

          snack_tel: 'Укажите Телефон представителя',
          snack_pos: 'Укажите Должность представителя',
          snack_names: 'Укажите ФИО представителя',
          snack_currency: 'Укажите валюту КП',
          snack_num: 'Заполните номер КП',
          po_sent: 'Коммерческое предложение отправлено!',

          login_by_email: 'Вход по почте',
          login_by_bin: 'Вход по БИН',
          login_username: 'Имя пользователя',
          login_next: 'Далее',
          login_pass: 'Пароль',
          login_enter: 'Войти',
          login_restore: 'Восстановить пароль',
          login_code: 'Код подтверждения',
          login_code_ph: 'Введите код подтверждения',
          login_code_enter: 'Ввести код подтверждения',
          login_set_pass: 'Установите пароль для Вашего аккаунта',
          login_pass_enter: 'Введите пароль',
          login_pass_repeat: 'Повторите пароль',
          login_pass_save: 'Сохранить пароль и войти',
          login_code_send: 'Отправить код подтверждения на почту',
          login_confirm_rules: 'Даю свое',
          login_confirm_rules2: 'Согласие',
          login_confirm_rules3: 'Согласие на обработку персональных данных',
          login_confirm_rules4: 'на обработку персональных данных',
          login_user_bin: 'БИН пользователя',
          login_forgot_pass: 'Забыли пароль?',
          login_enter_bin: 'Ввести БИН',
          login_email_sent: 'На вашу почту',
          login_email_sent2: 'было отправлено письмо с кодом подтверждения',

          login_rules_username: 'Введите Имя пользователя',
          login_rules_username_err: 'Вы неправильно ввели Имя пользователя',
          login_rules_pass_req: 'Пароль обязательное поле',
          login_rules_pass_dig: 'Пароль должен содержать минимум одну цифру',
          login_rules_code_dig: 'Код подтверждения состоит из 6 цифр',
          login_rules_confirm: 'Подтвердите свое согласие',
          login_rules_auth: 'Авторизация',
          login_rules_pass_rep_err: 'Пароли не совпадают',
          login_rules_pass_err: 'Вы ввели неправильный пароль',
          login_rules_no_user: 'Пользователя с таким именем не существует',
          login_rules_no_bin: 'Пользователя с таким БИН не существует',
          login_rules_code_err: 'Вы ввели неправильный код подтверждения',

          profile_status_approved: 'Подтвержденный',
          profile_status_not_approved: 'Непроверенный',
          profile_contractor: 'Контрагент',
          profile_email: 'Электронная почта',
          profile_phone: 'Номер телефона',
          profile_website: 'Веб-сайт',
          profile_actual_addr: 'Фактический адрес',
          profile_legal_addr: 'Юридический адрес',
          profile_manager: 'Основной менеджер',
          profile_tabs_info: 'ИНФО',
          profile_tabs_bank: 'РЕКВИЗИТЫ',
          profile_tabs_contracts: 'КОНТРАКТЫ',
          profile_tabs_contacts: 'КОНТАКТНЫЕ ЛИЦА',

          profile_table_bank: 'Банковские реквизиты',
          profile_table_currency: 'Валюта',
          profile_table_account: 'Номер счета',
          profile_table_bank_name: 'Наименование банка',
          profile_table_bik: 'БИК',

          profile_table_number: 'Номер',
          profile_table_name: 'Рабочее наименование',
          profile_table_state: 'Текущее состояние',
          profile_table_from: 'Действует с',
          profile_table_to: 'Действует по',
          profile_table_pay_currency: 'Валюта взаиморасчетов',

          profile_table_FIO: 'ФИО',
          profile_table_pos: 'Должность по визитке',
          profile_table_phone: 'Номер телефона',
          profile_table_email: 'Электронная почта',
        },
      }
    },
  },

}
